[package]
name = "validators-scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-jsonrpc-client = "0.6"
near-primitives = "0.17"
near-jsonrpc-primitives = "0.17"
near-token = "0.2"

serde = "1.0"
serde_json = "1.0"
easy-ext = "1.0"

futures = "0.3"
tokio = { version = "1", features = ["full"] }

color-eyre = "0.6"
