# fly.toml app configuration file generated for near-stake-delegators-scan on 2024-01-01T23:01:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "near-stake-delegators-scan"
primary_region = "yyz"

[build]

[[mounts]]
  source = "stake_delegators"
  destination = "/"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
