# fly.toml app configuration file generated for near-stake-delegators-scan on 2023-12-26T17:13:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "near-stake-delegators-scan"
primary_region = "yyz"

[build]

[mounts]
  source = "stake_delegators"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
